version: '3'
services:

    amphitryon_db:
        image: mongo:4.1.1
        restart : always
        ports:
            - 27017:27017
        container_name: amphitryon_db
        
    amphitryon_backend:
  
        build:
            context: .
            dockerfile: Server/Dockerfile
        restart : always
        ports:
          - 8080:8080
        depends_on:
            - amphitryon_db