version: '3'
services:

    amphitryon_db:
        image: mongo:4.1.1
        ports:
            - 27017:27017
        container_name: amphitryon_db
        
    amphitryon_graphdb:
        image: neo4j:3.5
        environment:
          NEO4J_AUTH: 'neo4j/secret'
        ports:
          - 7474:7474
          - 7687:7687
          
    amphitryon_backend:
  
        build:
            context: .
            dockerfile: Server/Dockerfile
        restart : always
        ports:
          - 8080:8080
        depends_on:
            - amphitryon_db
            - amphitryon_graphdb

    amphitryon_frontend: 

        build: 
            context: .
            dockerfile: Client/Dockerfile
        env_file: .env
        ports: 
            - 19000:19000
            - 19001:19001
            - 19002:19002