/**
 * @file    Global.ts
 * @author  Alexis Allemann & Alexandre Mottier
 * @date    22.03.2021
 * @brief   General application settings
 */

import Strings from './Strings';

export default {
  COLORS: {
    BLUE: '#28d7eb',
    DARK_GRAY: '#525252',
    FACEBOOK: '#4267B2',
    GOOGLE: '#DB4437',
    GRAY: '#d3d3d3',
    GREEN: '#28eb3c',
    ORANGE: '#eb9d28',
    PINK: '#eb2876',
    PRIMARY: '#eb3b28',
    TEXT: 'gray',
    WHITE: '#ffffff',
    YELLOW: '#d7eb28',
  },
  ICONS: {
    ABC: 'alphabetical',
    ADD_PROFILE: 'account-plus',
    ADD_TAG: 'plus-circle',
    ARROW_DOWN: 'color-helper',
    ARROW_LEFT: 'chevron-left',
    ARROW_UP: 'chevron-up',
    CALENDAR: 'calendar',
    CLOSE: 'close-circle',
    CLOSE_LOCATION: 'close',
    COPY: 'box-shadow',
    CREATE: 'plus-circle',
    DELETE: 'delete-outline',
    DISINFECTION: 'hand-water',
    DISTANCING: 'arrow-expand',
    EDIT: 'pencil',
    EDIT_IMAGE: 'circle-edit-outline',
    END_TIME: 'clock-time-nine',
    END_TIME_OUT: 'clock-time-nine-outline',
    FACEBOOK: 'facebook',
    FACEMASK: 'drama-masks',
    FILTER: 'filter',
    GOOGLE: 'google',
    HOME: 'home',
    INFO: 'information-outline',
    JOIN: 'calendar-check',
    LEAVE: 'location-exit',
    LOCATION: 'map-marker',
    LOCK: 'lock',
    LOGOUT: 'logout',
    MESSAGE: 'message-text',
    OPEN: 'home-lock-open',
    PROFILE: 'account',
    SAD: 'emoticon-sad-outline',
    SEARCH: 'magnify',
    SEND: 'send',
    START_TIME: 'clock-time-one',
    UNLOCK: 'lock-open-variant',
  },
  PRECISION: 2,
  SIZES: {
    ICON_BUTTON: 30,
    ICON_HEADER: 18,
    ICON_MENU: 20,
  },
  NAVIGATION: {
    AUTH_PROFILE_CONFIG: 'AUTH_PROFILE_CONFIG',
    AUTH_SIGN_IN: 'AUTH_SIGN_IN',
    AUTH_SIGN_UP: 'AUTH_SIGN_UP',
    AUTH_WELCOME: 'AUTH_WELCOME',
    HOST_CREATE_LOCATION: Strings.LOCATION_CREATE,
    HOST_EDIT_COVID: Strings.COVID_DATA,
    HOST_EDIT_HOST: Strings.HOST_EDIT,
    HOST_EDIT_LOCATION: Strings.LOCATION_EDIT,
    HOST_HOME: Strings.AGENDA,
    HOST_LOCATIONS: Strings.MY_LOCATIONS,
    HOST_PROFILE: Strings.PROFILE,
    STUDENT_CHAT: Strings.CHAT,
    STUDENT_CREATE_MEETING: Strings.MEETING_CREATE,
    STUDENT_EDIT_MEETING: Strings.MEETING_EDIT,
    STUDENT_HOME: Strings.AGENDA,
    STUDENT_HOST: Strings.HOST_DETAILS,
    STUDENT_LOCATION: Strings.LOCATION_DETAILS,
    STUDENT_PROFILE: Strings.PROFILE,
    STUDENT_SEARCH: Strings.SEARCH,
  },
  SETTINGS: {
    API_URL: 'https://amphitryon.herokuapp.com',
    GOOGLE_ID: '298748587556-mpio0261lovc0qkt660nbhgariolp1no.apps.googleusercontent.com',
    VERSION: 'Version 1.8',
  },
  SESSION_TOKEN_NAME: 'session_token_amphitryon',
};
