/**
 * @file    Strings.ts
 * @author  Alexis Allemann & Alexandre Mottier
 * @date    11.05.2021
 * @brief   Application strings
 */

export default {
  AGREEMENT:
    "En vous connectant, vous acceptez nos conditions générales. Pour en savoir plus sur l'apos;usage que nous faisons de vos données, consultez notre politique de confidentialité et notre politique en matière de cookies.",
  APP_NAME: 'Amphitryon',
  ASK_DELETE: 'Supprimer ?',
  ASK_LOCATION_DELETE: 'Etes-vous sûr de vouloir supprimer le lieu',
  ASK_MEETING_DELETE: 'Etes-vous sûr de vouloir supprimer la réunion',
  CHAT: 'Discuter',
  CHOOSE: 'Choisir',
  CREATED: 'Créé',
  COMMENTS_NULL: 'Veuillez mettre un commentaire',
  COPY_ID: 'Copier ID',
  COVID_DATA: 'Politique Covid :',
  CREATE: 'Créer',
  DELETE: 'Supprimer',
  DELETED: 'Supprimé',
  DEVELOPPING: 'Fonctionnalité en développement',
  DISINFECTION_NOT_REQUIRED: 'Désinfection non requise',
  DISINFECTION_REQUIRED: 'Désinfection requise',
  DISTANCING_NULL: 'Veuillez définir la distance requise',
  EDIT: 'Modifier',
  ERROR_ACCOUNT_ALREADY_EXISTS:
    'Ce compte est déjà rattaché à un compte Amphitryon, veuillez vous connecter',
  ERROR_CHAT_LOAD: 'Erreur lors de la récupération des messages',
  ERROR_CHAT_SEND: "Erreur lors de l'envoi du message",
  ERROR_FORBIDEN: "L'action effectuée est interdite pour l'utilisateur",
  ERROR_HOST_CREATE: "Erreur lors de la création de l'hébergeur",
  ERROR_HOST_LOAD: "Erreur lors de la récupération des détails de l'hébergeur",
  ERROR_HOST_LOCATIONS: 'Erreur lors du chargement de vos locations',
  ERROR_HOST_RESERVATIONS: "Erreur lors de l'obtention des réservations",
  ERROR_HOST_UPDATE: 'Erreur lors de la mise à jour du lieu',
  ERROR_INVLID_HOURS: 'Veuillez saisir des heures de début et de fin valides',
  ERROR_LOCATIONS_LOAD: 'Erreur lors du chargement des lieux',
  ERROR_LOCATION_CREATE: 'Erreur lors de la création du lieu',
  ERROR_LOCATION_DELETE: 'Erreur lors de la suppression du lieu',
  ERROR_LOCATION_LOAD: "Erreur lors de l'obtention du lieu",
  ERROR_LOCATION_UPDATE: 'Erreur lors de la mise à jour du lieu',
  ERROR_MEETING_CREATE: 'Erreur lors de la création de la réunion',
  ERROR_MEETING_DELETE: 'Erreur lors de la suppression la réunion',
  ERROR_MEETING_JOIN: "Erreur lors de l'inscription",
  ERROR_MEETING_LEAVE: 'Erreur lors de la désinscription',
  ERROR_MEETING_UPDATE: 'Erreur lors de la mise à jour de la réunion',
  ERROR_NOT_FOUND: "La ressource demandée n'a pas été trouvée",
  ERROR_OCCURED: "Une erreur s'est produite",
  ERROR_SEARCH_WITH_FILER: 'Erreur lors de la recherche de réunion',
  ERROR_SEARCH_WITH_ID: 'Erreur lors de la recherche de réunion',
  ERROR_SERVER: "Une erreur s'est produite sur le serveur",
  ERROR_UNAUTHORIZED: "Vous n'êtes pas autorisé à effectuer cette manipulation",
  ERROR_UNEXPECTED: "Une erreur inattendue s'est produite",
  ERROR_USER_CREATION: "Erreur lors de la création de l'utilisateur",
  ERROR_USER_GET_CREATED_MEETINGS: "Erreur lors du chargement des meetings de l'utilisateur",
  ERROR_USER_LOAD: "Une erreur s'est produite lors du chargement de l'utilisateur",
  ERROR_USER_LOAD_MEETINGS: 'Erreur lors du chargement de vos réunions',
  ERROR_USER_LOGIN: 'Erreur lors de la récupération des informations de votre compte',
  ESTABLISHMENT: 'Etablissement',
  HEIGVD: 'HEIG-VD',
  HOME: 'Accueil',
  HOST: 'Hébergeur',
  HOST_ADDRESS_CITY: 'Ville',
  HOST_ADDRESS_NAME: "Adresse de l'hébébergement",
  HOST_ADDRESS_NUMBER: "Numéro de l'adresse",
  HOST_ADDRESS_ZIP: 'NPA',
  HOST_CLOSED: 'Etablissement fermé',
  HOST_DATA: 'Informations générales',
  HOST_DESCRIPTION: "Description de l'hébébergement",
  HOST_DETAILS: 'Details hébergeur',
  HOST_EDIT: 'Modifier hébergeur',
  HOST_NAME: "Nom de l'hébébergement",
  HOST_OPEN: 'Etablissement ouvert',
  HOURS: 'Heures :',
  JOIN: 'Rejoindre',
  LEAVE: 'Quitter',
  LOCATION: 'Lieu',
  LOCATIONS_SEARCH: 'Recherche de lieux',
  LOCATION_CREATE: 'Créer un lieu',
  LOCATION_CREATED: 'Le lieu que vous avez soumis a bien été enregistré',
  LOCATION_DESCRIPTION: 'Description du lieu',
  LOCATION_DESCRIPTION_NULL: 'La description du lieu ne peut pas être nulle',
  LOCATION_DETAILS: 'Details du lieu',
  LOCATION_EDIT: 'Modifier lieu',
  LOCATION_NAME: 'Nom du lieu',
  LOCATION_NAME_NULL: 'Le nom du lieu ne peut pas être nul',
  LOCATION_NB_PEOPLE: 'Nombre de places disponibles',
  LOCATION_NB_PEOPLE_NULL: 'Le nombre de personnes doit être > 0',
  LOCATION_NONE: 'Aucun lieu',
  LOCATION_OPENING_HOURS_NULL: 'Veuillez définir au moins une plage horaire',
  LOCATION_TAGS_NULL: 'Veuillez définir au moins un tag à la réunion',
  LOCATION_UPDATE: 'Modifier le lieu',
  MASKS_NOT_REQUIRED: 'Masques optionnels',
  MASKS_REQUIRED: 'Masques obligatoires',
  MEETINGS_TO_COME: 'Réunions à venir créées',
  MEETING_CREATE: 'Créer une réunion',
  MEETING_CREATED: 'La réunion que vous avez soumise a bien été enregistrée',
  MEETING_DATE_BETWEEN: 'Entre les dates',
  MEETING_DATE_ERROR: "L'heure de fin doit être après l'heure de début",
  MEETING_DATE_TIME: 'Date / Heure',
  MEETING_DESCRIPTION: 'Description de la réunion',
  MEETING_DESCRIPTION_NULL: 'La description de la réunion ne peut pas être nulle',
  MEETING_ID_COPIED: "L'id de la réunion a été copié",
  MEETING_JOINED: 'Vous avez rejoint la réunion ',
  MEETING_LOCATION_NULL: 'Veuillez définir le lieu de la réunion',
  MEETING_NAME: 'Nom de la réunion',
  MEETING_NAME_NULL: 'Le nom de la réunion ne peut pas être nul',
  MEETING_NONE: 'Aucune réunion',
  MEETING_TAGS_NULL: 'Veuillez définir au moins un tag à la réunion',
  MEETING_UDPATE: 'Modifier la réunion',
  MEETING_UPDATE: 'Modifier la réunion',
  MESSAGE_TYPE: 'Tapez votre texte ici ...',
  MY_LOCATIONS: 'Mes lieux',
  NO: 'Non',
  OPENING_HOURS: 'Plages horaires',
  OPENING_HOURS_ADD: "Ajout d'horaires",
  OTHER: 'Autre',
  PRIVATE: 'Privée',
  PROFILE: 'Profil',
  PROFILE_CONFIGURATION: 'Configuration du profil',
  PROFILE_SEND: 'Finaliser le profile',
  PUBLIC: 'Publique',
  SAVE: 'Enregistrer',
  SAVED: 'Enregistré',
  SEARCH: 'Rechercher',
  SEARCH_ID: 'Id unique de la réunion',
  SEND: 'Envoyer',
  SIGN_IN: 'Connexion',
  SIGN_IN_CHOOSE: 'Veuillez choisir une option de connexion',
  SIGN_IN_WITH: 'Se connecter avec',
  SIGN_UP: 'Inscription',
  SIGN_UP_CHOOSE: "Veuillez choisir une option d'inscription",
  SIGN_UP_WITH: "S'inscrire avec",
  STUDENT: 'Etudiant',
  TAGS: 'Tags',
  TAGS_ADD: 'Ajout de tags',
  UPDATED: 'Mis à jour',
  USER_NAME: "Nom d'utilisateur",
  WELCOME: 'Bienvenue sur Amphitryon',
  YES: 'Oui',
};
